### ISSUE TITLE
NewTabImageOpen doesn't work properly.

### ISSUE THREAD

**Issue by beckyeeky** [NightLancer/PixivPreview#1]
The js didn't close the 404 tab properly.

I used Chrome/Tampermonkey here.

Tampermonkey suggested some syntax errors

**Comment by NightLancer** [comment]
What do you mean by "didn't close the tab properly"? It doesn't work at all, or in some cases(only for single arts/manga or on some pages)? 
Since I don't have regular version of  Chrome installed on my pc I can't test it myself right now, but I'll check this on weekends.
Script should work in FF/Greasemonkey, if you could test it in these conditions it would also helped.

_Btw, thanks for the feedback, since I hadn't know for sure if someone besides one fellow is using my script)_

**Comment by NightLancer** [comment]
@beckyeeky I've fixed the problem. You can update script by clicking here: https://github.com/NightLancer/PixivPreview/raw/master/NewTabImageOpen.user.js . Tested in FF 56.0/Greasemonkey(all ok, should work in newer versions too), Chrome 65.0/Tampermonkey - Opera 52.0/Tampermonkey("async" using is reported as error, but works fine). 
Does this work for you?

**Comment by NightLancer** [comment]
So, no errors occurs? Then I closing this issue.
