### ISSUE TITLE
Highlight color for followed artists not working.

### ISSUE THREAD

**Issue by drakom88** [NightLancer/PixivPreview#12]
Hello,
Pardon listing this as an issue, but the green color for followed artists isn't working for me on Chrome.
This is the only script I've found besides Patchouli that offers this (much needed) feature, yet neither is functioning.
Do you have advice/insight on this? Would you be willing/able to offer this function as a separate feature in exchange for some amount of cash? It would be greatly helpful to me, the Patchouli author seems to have given up.
Thank you for your consideration.

**Comment by drakom88** [comment]
Now it is working on the main page, but not if I go into a "tags" category. Is there a workaround for this?

**Comment by NightLancer** [comment]
@drakom88 Hello. No need for excuses - the "Issues" section was intended just for such a things) 

Glad to hear that someone else besides me have approved this feature as needed, when I was starting browsing a pixiv, I was wondering why site creators doesn't implemented this as native feature of their site! Even premium account doesn't have it, so I decided to write it myself.

As for Chrome bug - yea, there is an error after first installation of script and visiting main pixiv page. I haven't touched with it both of I'm using Firefox as main browser, and I already had my followed users stored in local browser storage. Same bug would've been occurred after cookies wiping as well in any case, so it is good you reported it and now I can fix it. 

> Now it is working on the main page, but not if I go into a "tags" category. Is there a workaround for this?

Yes, I think I can add coloring feature to search(tags) page. I couldn't worked there because it was not developed for this page. You can see correspondence of some major existing features and page they are implemented in the "PageType" section of script, not far from start:
![зображення](https://user-images.githubusercontent.com/19971564/101390863-275fb680-38cc-11eb-832f-79ce8cce339c.png)

...But this could work for "old" case. Pixiv has changed logic of loading of some pages(now 6 of them in total - was only 3), and I need to do a good few of reworking of my script logic as well to maintain this changes. With that - now it will be even harder to "extract" only coloring feature apart, not saying to properly implement it without bugs at all... And on top of it - pixiv changes pages layout pretty regularly, and if I leave extracted code as it is - it may stop working after another update, and to maintain two similar scripts at once would be not so comforting... And as for my current script - I will keep to maintaining it free of charge. 

For now, if preview annoys you, you can either set preview condition for "click", instead of mouse over(and open illusts pages by MMB instead of LMB), 
![зображення](https://user-images.githubusercontent.com/19971564/101394429-2e3cf800-38d1-11eb-8c00-ce724f332920.png)
or set a maximum possible preview delay (1.5s)
![зображення](https://user-images.githubusercontent.com/19971564/101394534-5593c500-38d1-11eb-9490-2af39af4669c.png)
Since preview is my main feature, I haven't implemented any "turn-off" switches for it... If you want to disable the preview feature rigth now - you can comment off all of lines in script starting with "setHover" and "setMangaHover" with two slashes (`//`) before them, and two lines of "onClickActions" to disable clicking feature.

Summarizing: thank you for the bug reporting and feedback that the feature is used by, it's a push for me to update script on the weekends or so. Currently I'm working at building my PC, so can't devote much of time for scripting right now. I will add basic tags page support at this weekend(which would work after refreshing the tags page with F5 or like), and make whole rework of script for dynamic page reloading after I got done with my PC.

**Comment by drakom88** [comment]
Thank you for the swift reply.

Yes, the coloring followed users would make premium 100x more worthwhile for me, they should hire you for sure.
It's such a time-saver compared to hovering over artist name every time to see if I've already gone through their works.

Thank you for your efforts, let me know if I can support you or your project financially somehow as I have no coding experience and cannot assist in that way. 
I respect that you want it to remain free, but I would like to donate to show gratitude for your work. (No offense intended, accept or decline as you wish.)
Getting tags implemented would be hugely helpful for me. 
Good luck with the new PC build!

**Comment by NightLancer** [comment]
@drakom88 Good news! I've managed to add to tags page support of coloring feature, and also of dynamic following/unfollowing database updating(newly followed authors arts will be highlighted on the next page, or on the same - after refreshing it).
![Screenshot_42](https://user-images.githubusercontent.com/19971564/101559556-067d8b00-39ca-11eb-9fc7-85ad3e74bdcd.png)

But - it is a "simple" solution, which will work only if tags page is opened directly from the browser address bar, or after reloading tags page(aka "F5") once after visiting it. Same for every other "new" pages, except for user's home/art/bookmarks pages... More simply - if something isn't working on some page, try to reload it - now it should work. To surpass this inconvenience much more time and efforts are needed, so I'll do it later, when I have more time for that. 

As for donation... I'll think about it when I update script for working properly without current workarounds. Anyway I have no international account right now, so I couldn't provide any even if I wanted) Firstly, work need to be done - with PC, and with script reworking, and then the rest)

**Comment by drakom88** [comment]
Wow, amazing! It is working quite well and so speedy.
Thank you so much, genius! Please take your time in working out any bugs, it is certainly good enoughl :bow:
