### ISSUE TITLE
Preview on click working with middle mouse button, rather than left click.

### ISSUE THREAD

**Issue by drakom88** [NightLancer/PixivPreview#13]
Hello again,

Previous to today, left clicking from a gallery would preview. Now middle click is previewing, making it difficult to open the image in a new tab. Not sure if it's something from my end. 
Something like a left click to preview option or creating a larger delay option for the "hover preview" or option to turn off the image preview entirely would be very helpful. Or perhaps I'm doing it wrong by using middle click to open in new tab?
Thank you very much for your consideration, advice, and work.

**Comment by NightLancer** [comment]
@drakom88 Hello. Thanks for the quick feedback, it makes me possible to fix issues in short period of time.

Yes, I tried to change 'click' preview event to 'mouseup', to save duplication of multiple code lines for registering/unregistering preview events on dynamic pixiv page changing(without actually reloading it), but seems forgot to test it's behavior as I'm always using 'mouseover' method... My apologies.

> Something like a left click to preview option or creating a larger delay option for the "hover preview" or option to turn off the image preview entirely would be very helpful.

That is what already existing in settings menu, and was working properly till the last update. 
Click case:
![зображення](https://user-images.githubusercontent.com/19971564/104845026-fd8eac00-58db-11eb-8826-96979e149661.png)
Delay case:
![зображення](https://user-images.githubusercontent.com/19971564/104845043-1008e580-58dc-11eb-9b87-68b9eaf0946b.png)

> Or perhaps I'm doing it wrong by using middle click to open in new tab?

No, you were doing all right. The only thing, that recent version of FireFox added own handler for MMB-click, for page panning(like in Chrome), and that feature conflicts with my script by intercepting clicks... 
![зображення](https://user-images.githubusercontent.com/19971564/104845172-a9d09280-58dc-11eb-96c8-94987f13097d.png)
I must to think how to bypass this, even though no one seem to complain about it yet(I don't know how many of users that are using my script have new Firefox as browser).

Regarding changing settings in menu, that was mentioned above: you still need to refresh entire page(for now), because after pixiv introduced dynamic page refreshing there are too much event state cases to re-register all of them on menu closing. It is still possible, but must be implemented very carefully, to not make bugs such like this one... (But, I suppose, one didn't change this options too frequently for this to being trouble for now?). 

At the current state, options:
"PREVIEW_SIZE", "ACCURATE_MANGA_PREVIEW", "DISABLE_MANGA_PREVIEW_SCROLLING_PROPAGATION", "DISABLE_SINGLE_PREVIEW_BACKGROUND_SCROLLING"
are applied immediately, without need of page reloading. For the rest of them you should close the menu(by clicking somewhere out of it) and reload the page. 

Making all settings "hot-applicable", and doing something with that Firefox MMB intercepting feature will be one of my next goals in fixing bugs, but I can't say when I will manage to implement this.

Thank you for appreciation the work I'm doing!

**Comment by NightLancer** [comment]
UPD: Please confirm that all is working in your case, so I may tag this issue as resolved.

**Comment by drakom88** [comment]
Yes working properly now on Chrome, thanks so much.
