### ISSUE TITLE
Follow check loads only 100 user ids

### ISSUE THREAD

**Issue by SADNESS81** [NightLancer/PixivPreview#23]
I tried clearing the local storage and it checks only the last 100 users I followed and it doesn't highlight most of them ( even though I have more than 100 artists followed )
![image](https://user-images.githubusercontent.com/115055225/194094067-7597d911-0181-42e6-a967-5e37b7bf0e09.png)
and there's another problem if I follow an artist on another tab it doesn't add them to the list 
I use Opera GX 91.0.4516.36 on windows 10 and tampermonkey 4.16

Edit: it seems that the problem is because I have artists followed privately, changed them to public and it works fine now

**Comment by NightLancer** [comment]
@SADNESS81 Hello. 
I deleted my stored followed users in Firefox, refreshed the page, and got full list of both public and private ones.
![зображення](https://user-images.githubusercontent.com/19971564/194381126-8029ba72-e88c-4227-a800-913150719db0.png)
![зображення](https://user-images.githubusercontent.com/19971564/194381180-231db175-03aa-4b15-84d7-a3c39230e52e.png)
![зображення](https://user-images.githubusercontent.com/19971564/194381197-62040705-e326-41b3-8dce-4f92026a17b5.png)
Tried on Chrome - no issue as well
![зображення](https://user-images.githubusercontent.com/19971564/194385800-77e8154d-8956-44f8-8800-4c9f1de9fd2b.png)
I don't really use Opera that much nowadays, but I believe my Opera is not GX version and las time I checked it was supporting scripts that works in Chrome and Tampermonkey. If there's some script errors in console you can post them so I knew at least approximate reason of why it doesn't load private users, but since all works fine both in Firefox and Chrome it's probably some Opera GX version issue(recently I heard that it also had some problems for streamers with OBS).

> and there's another problem if I follow an artist on another tab it doesn't add them to the list

Can you tell what site language you are using? Currently followed artists are being updated for english locale only, and only within same tab. For changes to be applied on another tab/different locale page should be refreshed. This approach is more consistent, as even if followed artists were fetched from localStorage every time(which would cause some extra impact), only newly loaded arts would've been colored(resulting of already loaded arts not being colored anyway). 

In some period of time script was re-coloring all arts on every new arts loaded, but it's just unnecessary performance impact and there are pages with different arts loading methods(such as main page), so backwards coloring of *all* instances could result in some arbitrary site blocks to be colored with green. So to eradicate that problem and both boost script performance script is coloring only newly loaded arts(which furthermore increases performance with auto-pagination option).

**Comment by SADNESS81** [comment]
> I deleted my stored followed users in Firefox, refreshed the page, and got full list of both public and private ones.

The problem seems to occur when you have more than 100 privately followed users. It seems that it's Pixiv's problem, not mine.

> If there's some script errors in console you can post them so I knew at least approximate reason of why it doesn't load private users

That's what concerns me that there were no script errors on the console, but it's alright now since I follow them publicly instead of privately.

> Can you tell what site language you are using? Currently followed artists are being updated for english locale only, and only within same tab. 

It was most likely the same issue because I was following them privately.

> For changes to be applied on another tab/different locale page should be refreshed. This approach is more consistent, as even if followed artists were fetched from localStorage every time(which would cause some extra impact), only newly loaded arts would've been colored(resulting of already loaded arts not being colored anyway).

Now that I think about it, that makes more sense.

**Comment by NightLancer** [comment]
>The problem seems to occur when you have more than 100 privately followed users.

Hmm, strange limitation... I'll try to keep that in mind. 

But since you circumvented this issue - I'm considering it as resolved.
