### ISSUE TITLE
script crashes when you like a post or follow user and close the tab

### ISSUE THREAD

**Issue by reaseno** [NightLancer/PixivPreview#24]
The script crashes when you like a post or follow a user and close the tab right after. At least the CPU load increases until you kill the process.

Maybe it is also necessary that several tabs of pixiv are open.

**Comment by NightLancer** [comment]
@reaseno Hello. I never meet anything of that sort so I need more info:

- what is your browser and script manager versions
- where "script crashing" at all if you already closed said tab? On other tabs, I guess? If so — tell what is exactly not working, as there are several different features of(like preview, pagination, coloring) and they are working independently when it's possible. 
- on what pages this is happening(is it general or affect only specific pages)
- post screenshot/console log(F12) with script errors listed

And while I do have some "easy followage update" - there are no features attached to like button. And I tried to follow new artist and immediately closed page with Ctrl+W - but another opened page didn't changed at all.

**Comment by reaseno** [comment]
Tested in newly installed Chrome Version 113.0.5672.127
Tampermonkey v4.19.0

- log into pixiv
- open a tab with https://www.pixiv.net/discovery
- open around three unfollowed user pages
- follow a user and press CTRL-W
- this should increase CPU load
- do this a second time, will result in full CPU load
- some times more and pixiv can't load anymore

There are no log entries, as the script seem to just run in infinite loops.

**Comment by NightLancer** [comment]
@reaseno 

I tried exact given action but still can't reproduce neither in Firefox nor in Chrome. There's no CPU peak/constant usage for me and no site/script hanging - consecutive pages opens just fine and on currently opened discovery page previewing and coloring continue to work as intended. 

Moreover, script cant even possibly run "in infinite loops"(or at all) on already closed pages. Different pages have no access between themselves directly - scripts included. At max, if you opening pixiv first time of a day(and after 23 hours of previous follow check) and in those several seconds will try to follow someone - it's just it will not be added to the list, and will renew in other 23 hours.

If you are getting 100% CPU load this means something going wrong either with browser/its settings, with script manager or PC hardware. It's really hard to tell without any logs(and in case of "infinite loop" there would've been constant repetitive messages). If you sure your OS is not on [faulty] HDD, really old CPU and you are not running with 95% RAM usage then it may be some "updates" in browser or script manager. As I'm not actively using Chrome - I tried with 95.0.4638.69 browser version and 4.16.1 Tampermokey version - all works fine.

That aside, you can try to "fix" this by commenting out ~814 line `//followage(this, toFollow);` or even that entire `if` block. Because no matter what changes I'll do to the code — if you going to force-close tab they will not be executed anyway(and while I tried — 1/3 of times even pixiv's server didn't received following action). 

But you also said that "script crashes after liking a post" — so what exactly happens? Script has not listener to like button whatsoever. But, it's not the first time when pixiv could've released another major update on their site and you have completely different layout already(that already happened 2 times before). If so - I still have old one, if there are some changes on site I'm going to see them not sooner than in 2 weeks. Tho I managed to fix some update-related bugs before having update before — at least I had screenshots and logs for that. But without bug reproducing and any logs it's almost impossible to fix something because I simply don't know what exactly is broken.

**Comment by reaseno** [comment]
I have looked at the whole thing again. Especially because of your reference to the Likes, which your script does not handle.

Meanwhile I see that the constant CPU load occurs even without loading your script. I had tested this months ago, but I didn't know then that the cause was Follow and Tab Close. And so your script remained as the cause in my head 😅

The cause is this script instead:
https://www.pixiv.net/OneSignalSDKWorker.js

The only strange thing is that you couldn't reproduce it.

It can't be due to a lack of hardware, 8 core CPU with 32GB RAM that are just about 40% utilized. Also, I can reproduce it on another computer.

Finally, I have nothing more to say than, thank you very much for your really helpful javascript.

**Comment by NightLancer** [comment]
>Meanwhile I see that the constant CPU load occurs even without loading your script.

That's exactly what I was suggesting when referred to possible hardware limit(there was once such errors when someone browsed pixiv with my script under 99% RAM usage which led to random errors)

>The cause is this script instead:
https://www.pixiv.net/OneSignalSDKWorker.js

Nice to know that you found the cause.

>The only strange thing is that you couldn't reproduce it.

Well I do have uBlock always enabled so it may just block some faulty part of that cpu overusage scenario, it does have "onesignal" domain blocked:
![зображення](https://github.com/NightLancer/PixivPreview/assets/19971564/026fcba2-38a5-438d-98c5-6ed87a75fd8f)

So you can try to add it to the blocking list and maybe this will fix problem for you?..
<br>

Glad to hear that)

**Comment by reaseno** [comment]
It is also in my ublock list. Disabling it does not solve the problem either.
I have pointed out the problem to pixiv.
