### ISSUE TITLE
Feature request: Option to replace thumbnails

### ISSUE THREAD

**Issue by unknown--** [NightLancer/PixivPreview#27]
There's another userscript that does this:  https://github.com/kepstin/Fix-pixiv-thumbnails
but it seems to conflict with your script. I'm managed to mostly get an older version of it working (20230328.1) with some CSS rules but the manga preview seems to include other images from submissions that I've previously previewed on the page.

**Comment by NightLancer** [comment]
To be honest incomplete thumbnails were part of the reason for my script. But even having "correct" ones was not enough for me since 240x240 static preview doesn't really show any details anyway, so having 1200px preview instead was solving both of those problems[eliminating the very need to do anything with default previews].

I tried 28.1 version and previews are becoming misplaced and overscaled with it(I assume because of that script injecting css rules). For multi-images I'm not flushing previous preview in case of accidental mouse-out of it and having like 100 images reloading from 0 anew - so they are being reset only if next previewed id differs from previous one. That script seems overrides much enough to somehow break this caching. And that caching matters a lot outside of Japan 'cause even despite my 100MB/s speed images are loading at 1MB/s speed, so removing that is not really the option. I can't even imagine how bad it is for anyone having 100Mb/s or less.

And I'm not using pixiv that much lately... I still make quick-fixes for their eventually-changing selectors, but that's simple&quick and relies on my code which I know where things are located. Tailoring it for separate update-able script would've complicate things as if pixiv was updating as often. So it ends up as which script's functionality you want to preserve more.

But in case you are ok with your CSS fixes and that script not updating, you can edit code in mine one in `imgsArrInit` function at 1415 line(may differ for you) and change:
`if (currentImgId != lastImgId)`
to
`if (true)`
(to make edit less complicated). 
That way multiple images will no longer be caching for you within script(you can still temporarily see browser-cache of them tho before they get fully replaced from server with new ones). This is easiest "fix" I can see here while keeping both scripts.

**Comment by unknown--** [comment]
Thanks for looking into it. I did figure your scripts intentions had something to do with the cropped thumbnails. I've gotten used to looking at each complete thumb thanks to the other script but your gallery feature was too useful to give up on.

I tried tinkering after I made this issue and came upon two solutions. One was filtering out the child elements in the mangaContainer where their src values weren't direct image links and the other is just reducing 'imgsArrInit' to a single loop that recreates imgsArr on each hover.

I did try your suggestion but I still ended up with some previous images. I guess because the other script creates a srcset and the browser uses that despite your script erasing the src value.

**Comment by NightLancer** [comment]
> I did try your suggestion but I still ended up with some previous images. I guess because the other script creates a srcset and the browser uses that despite your script erasing the src value.

if that's the case, you can try double
```
imgsArr[j].src = '';
```
to

```
imgsArr[j].src = '';
imgsArr[j].srcset = '';
```
or any other data-field that script uses for storing its source. Final result depends on browser processing it tho, so it's not guaranteed to work out.
