### ISSUE TITLE
Pixiv update broke a preview feature

### ISSUE THREAD

**Issue by MsgLosers** [NightLancer/PixivPreview#6]
Looks like another update on pixiv broke the preview function. Specifically on the search page that returns this page:
www pixiv net/en/tags/searchword/artworks?s_mode=s_tag

Wanted to let you know. :)

**Comment by NightLancer** [comment]
@MsgLosers Thanks for the information! I am, personally, rarely visit the search section, so such notifications are very appreciated. That was easy to fix) [1.43.1](https://github.com/NightLancer/PixivPreview/raw/master/PixivPreview.user.js) _(Update script by this link, please, because `@download` directive was lost in second commit while transferring from greasy, and I don't know, whether it will be updated automatically\)_
Also uploaded some previous updates. Changed one option:
`previewSize = 0;` It means preview size will be calculated automatically with "live" dependence of current screen size, but you can still manually set size of preview to `1200` or `600`.
And added highlighting feature for "bookmarks of other users" pages. Also updated [readme](https://github.com/NightLancer/PixivPreview/blob/master/README.md) for more clear description of the settings.
