### ISSUE TITLE
Using greasemonkey api to store and retrieve custom preferences

### ISSUE THREAD

**Issue by livelazily** [NightLancer/PixivPreview#8]
Custom preferences reset to default every time after auto update of the script, this is very annoying.

[GM.setValue](https://wiki.greasespot.net/GM.setValue) can store the preferences value, 
[Gm.getValue](https://wiki.greasespot.net/GM.getValue) can retrieve the preferences value.

Please add this feature for the custom preferences

**Comment by NightLancer** [comment]
@livelazily Hello. 

Yes, I don't like this too. But if I simply save settings with `GM.setValue` and then will be always loading them with `Gm.getValue` — then there would be no way to change them, since they are setting manually in the code. To solve this problem, there should be desingned some on-site menu for script settings. And while I better in raw coding then in site layout designing, I always delayed this for "better times"... 
The time has come, I guess. 

I will make some menu for my settings to the next update. I think the best way will be to embed it into the newly released pixiv menu.

P.S. I'm personally prefer localstorage over GM methods, since I'm trying to keep my code compatible with all versions of script managers(old GM, new GM, TM). I'm using this method for storing followed users id and other related data, and it works pretty fine.

P.P.S Anyway - thanks for the feedback. It makes me fight my laziness and do things.

**Comment by NightLancer** [comment]
@livelazily

Phew. Menu design took more effort than inner working logic development(despite menu is quite primitive and principle of work is not). But I did it. It seems complicated development I like more then visual site designing. 

Take my apology for such an long term of waiting. The real work took near 3-4 weekend evenings, but other life circumstances made me finish my work in such a late. I wanted to make all changes in one update, as I promised. And for that, I thinked of different approaches, сonsidering feature of settings saving/loading compatibility with future possible update of settings. 

For now, settings menu is available by the clicking on "Related services" icon in right top corner of site page.
![зображення](https://user-images.githubusercontent.com/19971564/77829601-bad0cd00-712b-11ea-8823-4f2cf968303e.png)
Click on the button on left of the setting name to change it value. I've made some foolproof protection this time, for be sure that somebody will not enable both preview via mouse click and delay before preview. Settings are stored and applied immediately after menu is closed on the second clicking on "Related services" button. Every action("Settings loaded"/"Settings saved") is logged in console. Possible primitive errors taken into account and should not be occurred, others should been logged in console as well, so please report it, if you run into some.

I will add some my own designed button or make it more comfortable to open sometime later. 
Also, current menu design is quite simple, I'll look for making it more friendly-looking too. Any suggestions are appreciated.

**Comment by NightLancer** [comment]
@livelazily

Uptated a script using your tips, waiting for your reply.

**Comment by livelazily** [comment]
Good job!
